accounts/urls.py
"""
Author: Elijah Kinyanjui
(c) Copyright by HugosLabs ltd

File:
Description:


"""
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

urlpatterns = [
    path('send_login_email', views.send_login_email, name="send_login_email"),
    path('login', views.login, name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
]

lists/urls.py
"""
Author: Elijah Kinyanjui
(c) Copyright by HugosLabs ltd

File: 
Description: 


"""
from django.urls import path

from lists import views

urlpatterns = [
    path('<list_id>/', views.view_list, name="view_list"),
]

superlists/urls.py
from django.contrib import admin
from django.urls import path, include

from lists import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('lists/', include('lists.urls')),
    path('accounts/', include('accounts.urls'))
]

accounts/models.py
from uuid import uuid4

from django.db import models


class User(models.Model):
    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True


def gen_uuid():
    return uuid4().hex


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=gen_uuid, max_length=40)

lists/models.py
from django.db import models
from django.urls import reverse


class List(models.Model):
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    class Meta:
        ordering = ('id',)
        unique_together = (('text', 'list'),)

    def __str__(self):
        return self.text

lists/forms.py
"""
Author: Elijah Kinyanjui
(c) Copyright by HugosLabs ltd

File: 
Description: 


"""
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.ModelForm):

    def save(self, for_list, *args, **kwargs):
        self.instance.list = for_list
        return super().save()

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg',
                'id': "new_item_input",
            })
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


class ExistingListItemForm(ItemForm):

    def __init__(self, *args, for_list, **kwargs):
        super().__init__(*args, **kwargs)
        self.for_list = for_list
        self.instance.list = for_list

    def save(self, *args, **kwargs):
        return forms.ModelForm.save(self)

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

accounts/views.py
from django.contrib import messages, auth
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse

from accounts.models import Token


def send_login_email(request):
    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse('login') + f'?token={token.uid}'
    )
    send_mail(
        'Your login link for Superlists',
        f'Use this link to log in:\n\n{url}',
        'noreply@superlists',
        [email],
    )
    messages.add_message(
        request,
        messages.SUCCESS,
        "Check your email, we've sent you a link you can use to log in."
    )
    return redirect('/')


def login(request):
    token = request.GET.get("token")
    user = auth.authenticate(request, uid=token)
    if user:
        auth.login(request, user)
    return redirect('/')

lists/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect

from lists.forms import ItemForm, ExistingListItemForm
from lists.models import Item, List


def view_list(request, list_id):
    item_list = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=item_list)
    if request.method == 'POST':
        form = ExistingListItemForm(request.POST, for_list=item_list)
        if form.is_valid():
            form.save()
            return redirect(item_list)
    context = {"list": item_list, "form": form}
    return render(request, "lists/list.html", context=context)


def home_page(request):
    if request.method == 'POST':
        return new_list(request)
    return render(request, "lists/home.html", {"form": ItemForm()})


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        item_list = List.objects.create()
        form.save(item_list)
        return redirect(item_list)
    return render(request, "lists/home.html", {"form": form})

accounts/templates/accounts/login_email_sent.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Superlists | Email Sent</title>
  </head>
  <body>
    <h1>Email sent</h1>
    <p>
      Check your email, you'll find a message with a link that will log into the
      site.
    </p>
  </body>
</html>

lists/templates/lists/home.html
{% extends "base.html" %}

{% block header_text %} Create a To-Do list {% endblock %}

{% block content %}

    <form method="POST" action="{% block form_action %}{% url 'home' %}{% endblock %}">
      {{ form.text }}
      {% csrf_token %}
{#    {% if form.text.errors %}#}
        <div class="form-group has-error">
        <span class="help-block">{{ form.text.errors }}</span>
        </div>
{#    {% endif %}#}
    </form>
    {% block list_table %}
    {% endblock %}
{% endblock %}

lists/templates/lists/list.html
{% extends "lists/home.html" %}
{% block header_text %} Your To-Do list {% endblock %}
{% block form_action %}{% url 'view_list' list.id %}{% endblock %}
{% block list_table %}
<table id="to-do-list-table" class="table">
  <tbody>
    {% for item in list.item_set.all %}

    <tr class="justify-content-start">
      <td>{{ forloop.counter }}. {{ item.text }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="{% static 'lists/style.css'%}" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    <meta charset="UTF-8" />

    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>To-Do lists</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <a href="/" class="navbar-brand">Superlists</a>
          {% if user.email %}
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-bar-text">Logged in as {{ user.email }}</li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          </ul>
          {% else %}
          <form
            action="{% url 'send_login_email' %}"
            method="post"
            class="navbar-form navbar-right"
          >
            <label for="id_email">Enter email to log in:</label>
            <input
              id="id_email"
              type="email"
              name="email"
              class="form-control"
            />
            {% csrf_token %}
          </form>
          {% endif %}
        </div>
      </nav>
      {% if messages %}
      <div class="row">
        <div class="col-md-8">
          {% for message in messages %} {% if message.tags == 'success' %}
          <div class="alert alert-success">
            {% else %}
            <div class="alert alert-warning">{% endif %} {{ message }}</div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        <div class="row">
          <div class="col-md-6 mx-auto">
            <div class="text-center">
              <h1>{% block header_text %}{% endblock %}</h1>
              {% block content %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>